name: Deploy SAPL site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-first-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Create symlink
        run: |
          latest_doc=$(ls -1d docs/*/ | sort | tail -n 1)
          ln -s $(basename $latest_doc) docs/latest
      - name: Install dependencies
        run: bundle install

      - name: Build first website
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy first website
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

  Build-second-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: bundle install

      - name: Build second website
        run: bundle exec jekyll build --config md-files/saplReference/_config.yml
        env:
          JEKYLL_ENV: production

      - name: Deploy second website
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./md-files/saplReference/_site